name: "Upload S3 (1GB)"

on:
  workflow_dispatch:

jobs:
  upload:
    name: Upload
    runs-on: [self-hosted, macos, arm64]

    steps:

      - name: Create Large File
        run: |
          openssl rand -out large_file -base64 $(( 2**30 * 3/4 ))

      - name: Upload to S3
        env:
          S3_PATH: mirego-gh-shr-test
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          START_TIME=$SECONDS
          aws s3 cp large_file s3://mirego-gh-shr-test/github_runner
          ELAPSED_TIME=$(($SECONDS - $START_TIME))
          echo "Upload time: $(($ELAPSED_TIME/60)) min $(($ELAPSED_TIME%60)) sec" >> $GITHUB_STEP_SUMMARY
